name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzNlMDI4MTMtMmFlNi00ZjUyLWFjZjQtMTg1MWVjMmI3OTU2IiwidGVuYW50X2lkIjoiN2I4YWU4YTAwZjhhNGZiMTcwZDEyOWRlZjg2NWQwZjYwMDkwOTliYzFkNDc1ZDU3NTk0NzhjMzYzYmQzMzRkMSIsImludGVybmFsX3NlY3JldCI6ImI1MzQ2OGJhLTAwYzctNDMxZC1hYjc3LTY4ZDZmYjcyNTAyYSJ9.nb_FQFA94p7b2rKNA4IGR-TG3MNjFdxXSTXbov861ns"

JWT_SECRET="SECRETS123"

